apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  redis_url: "redis://link-persona-redis.rp2iew.0001.apne1.cache.amazonaws.com:6379"
  s3_bucket_name: "link-persona-user-assets-production"
  cloudfront_domain: "dgp0k5j9yz9ro.cloudfront.net"
