apiVersion: v1
kind: ServiceAccount
metadata:
  name: rails-api
  namespace: default
  annotations:
    # terraform output rails_api_irsa_role_arn の値を設定する
    eks.amazonaws.com/role-arn: arn:aws:iam::276713243798:role/link-persona-rails-api-role
